# Form implementation generated from reading ui file 'spam_gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(463, 252)
        MainWindow.setMinimumSize(QtCore.QSize(463, 252))
        MainWindow.setMaximumSize(QtCore.QSize(463, 252))
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.DialogWarning)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.type_text = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.type_text.setGeometry(QtCore.QRect(10, 150, 441, 31))
        self.type_text.setObjectName("type_text")
        self.check_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.check_btn.setGeometry(QtCore.QRect(380, 190, 71, 31))
        self.check_btn.setObjectName("check_btn")
        self.warning_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.warning_message.setGeometry(QtCore.QRect(10, 60, 441, 41))
        self.warning_message.setText("")
        self.warning_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.warning_message.setIndent(0)
        self.warning_message.setObjectName("warning_message")
        self.reset_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(10, 190, 71, 31))
        self.reset_btn.setObjectName("reset_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spam detector"))
        self.type_text.setPlaceholderText(_translate("MainWindow", "Wpisz wiadomość po angielsku . . ."))
        self.check_btn.setText(_translate("MainWindow", "Sprawdź"))
        self.reset_btn.setText(_translate("MainWindow", "Resetuj"))
